"""Add campaign payout fields and tracking link stats

Revision ID: 929cea994b1b
Revises: b7f8d92e1234
Create Date: 2026-02-06 21:55:04.664073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929cea994b1b'
down_revision: Union[str, None] = 'b7f8d92e1234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_progress_agent_id'), table_name='agent_progress', if_exists=True)
    op.drop_index(op.f('ix_agent_progress_date'), table_name='agent_progress', if_exists=True)
    op.add_column('campaigns', sa.Column('description', sa.String(), nullable=True))
    # Add target_url as nullable first, set default, then make NOT NULL
    op.add_column('campaigns', sa.Column('target_url', sa.String(), nullable=True))
    op.execute("UPDATE campaigns SET target_url = 'https://example.com' WHERE target_url IS NULL")
    op.alter_column('campaigns', 'target_url', nullable=False)
    op.add_column('campaigns', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('campaigns', sa.Column('spent', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('payout_per_view', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('points_per_view', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('total_views', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('total_unique_views', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_contact_pool_is_assigned'), table_name='contact_pool', if_exists=True)
    op.drop_index(op.f('ix_contact_pool_phone'), table_name='contact_pool', if_exists=True)
    op.drop_index(op.f('ix_contact_pool_tenant_id'), table_name='contact_pool', if_exists=True)
    op.add_column('tracking_links', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('tracking_links', sa.Column('unique_view_count', sa.Integer(), nullable=True))
    op.alter_column('tracking_links', 'target_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_vcf_batches_agent_id'), table_name='vcf_batches', if_exists=True)
    op.drop_index(op.f('ix_vcf_batches_status'), table_name='vcf_batches', if_exists=True)
    op.drop_index(op.f('ix_vcf_batches_tenant_id'), table_name='vcf_batches', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vcf_batches_tenant_id'), 'vcf_batches', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_vcf_batches_status'), 'vcf_batches', ['status'], unique=False)
    op.create_index(op.f('ix_vcf_batches_agent_id'), 'vcf_batches', ['agent_id'], unique=False)
    op.alter_column('tracking_links', 'target_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tracking_links', 'unique_view_count')
    op.drop_column('tracking_links', 'view_count')
    op.create_index(op.f('ix_contact_pool_tenant_id'), 'contact_pool', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_contact_pool_phone'), 'contact_pool', ['phone'], unique=False)
    op.create_index(op.f('ix_contact_pool_is_assigned'), 'contact_pool', ['is_assigned'], unique=False)
    op.drop_column('campaigns', 'total_unique_views')
    op.drop_column('campaigns', 'total_views')
    op.drop_column('campaigns', 'points_per_view')
    op.drop_column('campaigns', 'payout_per_view')
    op.drop_column('campaigns', 'spent')
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'target_url')
    op.drop_column('campaigns', 'description')
    op.create_index(op.f('ix_agent_progress_date'), 'agent_progress', ['date'], unique=False)
    op.create_index(op.f('ix_agent_progress_agent_id'), 'agent_progress', ['agent_id'], unique=False)
    # ### end Alembic commands ###
